### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by small-tree** [easemob/easeui#170]
错误: 找不到符号 符号:   方法 deliverOnlineOnly(boolean) 位置: 类型为EMCmdMessageBody的变量 body	

错误: 找不到符号 符号:   方法 isDeliverOnlineOnly() 位置: 类型为EMCmdMessageBody的变量 body |

**Comment by githubzhaoliang** [comment]
SDK是否升级到了最新版本，该接口是3.4.3版本中提供的

**Comment by small-tree** [comment]
我从官网下载 吧，这个项目下载 easeui module,导入就报错了

**Comment by fujiangren** [comment]
导入好慢 一直下载

**Comment by jinanzhuan** [comment]
> 导入好慢 一直下载

从github上导入代码普遍都比较慢，您可以看看这篇文章：https://blog.csdn.net/xyl295528322/article/details/107287659
