### ISSUE TITLE
编译报错啊！！！！！

### ISSUE THREAD

**Issue by workertao** [easemob/easeui#177]

**Comment by jinanzhuan** [comment]
请发送一下报错信息，我们和您共同分析一下。
另外，easeui的升级版EaseIMKit已经有相关分支，且EaseIMKit也支持远程库依赖了，后面将和SDK的更新同步进行更新，欢迎您进行使用。

**Comment by jinanzhuan** [comment]
您可以选择使用uikit的远程库，参考文档：http://docs-im-beta.easemob.com/document/android/easeimkit.html
