### ISSUE TITLE
导入easeUI model 报错

### ISSUE THREAD

**Issue by Qjh524** [easemob/easeui#183]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Lanmei\Product\XuYangXueJun\easeui\build.gradle' line: 39

* What went wrong:
A problem occurred evaluating project ':easeui'.
> Could not find method testImplementation() for arguments [com.android.support.test.espresso:espresso-core:2.2.2, build_5m3d1r129n9vqgygjt200zoqr$_run_closure2$_closure7@2fd01d59] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE FAILED in 0s
Could not find method testImplementation() for arguments [com.android.support.test.espresso:espresso-core:2.2.2, build_5m3d1r129n9vqgygjt200zoqr$_run_closure2$_closure7@2fd01d59] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
Open File

**Comment by jinanzhuan** [comment]
请查看您项目中是否使用的compile，gradle版本是否较低。如果是这个问题的话，建议进行如下操作：
1、升级android Studio到3.2以上。
2、将gradle版本升级到4.6以上。
另外，easeui的升级版EaseIMKit已经有相关分支，且EaseIMKit也支持远程库依赖了，后面将和SDK的更新同步进行更新，欢迎您进行使用。
