### ISSUE TITLE
ERROR: Failed to resolve: com.hyphenate:hyphenate-sdk:3.6.7 

### ISSUE THREAD

**Issue by small-tree** [easemob/easeui#188]
请更新 demo

**Comment by jinanzhuan** [comment]
请更新到最新版的SDK即可。
另外，easeui的升级版EaseIMKit已经有相关分支，且EaseIMKit也支持远程库依赖了，后面将和SDK的更新同步进行更新，欢迎您进行使用。

**Comment by jinanzhuan** [comment]
> 请更新 demo

在EaseIMKit中将会跟随SDK更新，且将及时更新其中依赖的SDK版本，且切换到EaseIMKit分支进行使用。
另外，EaseIMKit是easeui的升级版，且已经有相关分支，EaseIMKit也支持远程库依赖了，后面将和SDK的更新同步进行更新，欢迎您进行使用。
