### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by BNDG** [easemob/easeui#189]
多测试

**Comment by BNDG** [comment]
fk 浪费时间!

**Comment by Lijian1122** [comment]
您好,把easeui\easeui\build.gradle 中的 api 'com.hyphenate:hyphenate-sdk:3.6.7' 改为  api 'com.hyphenate:hyphenate-sdk:3.6.6' ，编译报错是因为 3.6.7马上发布，改了sdk 版本号，您可以先用 3.6.6.

**Comment by Lijian1122** [comment]
您好 com.hyphenate:hyphenate-sdk:3.6.7 已经发布了 您可以试试最新版的SDK
