### ISSUE TITLE
卡顿问题

### ISSUE THREAD

**Issue by kulong51** [easemob/easeui#202]
问题描述：
应用长时间没登录，等下次登录会有几万条消息推送过来，导致界面卡顿无法操作，这种情况要怎么处理呢？

**Comment by jinanzhuan** [comment]
从服务端下发的离线消息是有时间和条数限制的。如果方便的话，请提供给我们一下日志，我们将进行核查，谢谢！

**Comment by jinanzhuan** [comment]
> 问题描述： 应用长时间没登录，等下次登录会有几万条消息推送过来，导致界面卡顿无法操作，这种情况要怎么处理呢？

1、从服务端下发的离线消息是有时间和条数限制的。
2、EaseConversationListFragment解决过RecyclerView的item没有复用的问题。您可以检查下是否有类似的问题。
3、可以在EMMessageListener#onMessageReceived中增加一些逻辑处理，比如在消息量大的时候1s才刷新一次页面，而不是按照接收消息的频率进行刷新。
