### ISSUE TITLE
文档总要更新一下吧

### ISSUE THREAD

**Issue by LockeyWu** [easemob/easeui#203]
http://docs-im.easemob.com/im/android/other/easeimkit
在官方查看的好多对不上新版
而且自定义 消息界面没有写清楚，还有对应聊天界面属性（昵称显示，状态栏显示）

**Comment by jinanzhuan** [comment]
感谢您提出的宝贵意见，针对您提出的没有描述清楚的模块，我们将进行改进，同时也希望您进一步关注EaseIMKit，谢谢！

**Comment by jinanzhuan** [comment]
> http://docs-im.easemob.com/im/android/other/easeimkit
> 在官方查看的好多对不上新版
> 而且自定义 消息界面没有写清楚，还有对应聊天界面属性（昵称显示，状态栏显示）

我们已经根据您提出的自定义消息部分及昵称显示部分增加的说明。请问您所说的状态栏显示，是指没有进行说明还是说明不够清晰呢？其他部分您是否还有认为表达不够清晰的，请您及时向我们指出，谢谢！

**Comment by LockeyWu** [comment]
&nbsp;主要新版 做这块自定义 修改起来 比较麻烦 不知道从哪里入手






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "easemob/easeui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 下午5:11
收件人:&nbsp;"easemob/easeui"<easeui@noreply.github.com&gt;;
抄送:&nbsp;"Lock &amp; Key"<784859276@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [easemob/easeui] 文档总要更新一下吧 (#203)





  
http://docs-im.easemob.com/im/android/other/easeimkit
 在官方查看的好多对不上新版
 而且自定义 消息界面没有写清楚，还有对应聊天界面属性（昵称显示，状态栏显示）
  
我们已经根据您提出的自定义消息部分及昵称显示部分增加的说明。请问您所说的状态栏显示，是指没有进行说明还是说明不够清晰呢？其他部分您是否还有认为表达不够清晰的，请您及时向我们指出，谢谢！

**Comment by jinanzhuan** [comment]
> &nbsp;主要新版 做这块自定义 修改起来 比较麻烦 不知道从哪里入手
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "easemob/easeui" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月4日(星期四) 下午5:11 收件人:&nbsp;"easemob/easeui"<easeui@noreply.github.com&gt;; 抄送:&nbsp;"Lock &amp; Key"<784859276@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [easemob/easeui] 文档总要更新一下吧 (#203) http://docs-im.easemob.com/im/android/other/easeimkit 在官方查看的好多对不上新版 而且自定义 消息界面没有写清楚，还有对应聊天界面属性（昵称显示，状态栏显示） 我们已经根据您提出的自定义消息部分及昵称显示部分增加的说明。请问您所说的状态栏显示，是指没有进行说明还是说明不够清晰呢？其他部分您是否还有认为表达不够清晰的，请您及时向我们指出，谢谢！ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这是我们修改后的文档：[增加自定义消息类型及其布局](http://docs-im.easemob.com/im/android/other/easeimkit#%E5%A2%9E%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B6%88%E6%81%AF%E7%B1%BB%E5%9E%8B%E5%8F%8A%E5%85%B6%E5%B8%83%E5%B1%80)
请您看一下，如果文档还是没有表述清楚，或者使用过程中有其他问题，欢迎继续向我们反馈！

**Comment by LockeyWu** [comment]
http://docs-im.easemob.com/im/android/other/easeimkit#创建会话列表界面




这些昵称 和头像 如何获取&nbsp; 怎么设置

**Comment by jinanzhuan** [comment]
> [http://docs-im.easemob.com/im/android/other/easeimkit#创建会话列表界面](http://docs-im.easemob.com/im/android/other/easeimkit#%E5%88%9B%E5%BB%BA%E4%BC%9A%E8%AF%9D%E5%88%97%E8%A1%A8%E7%95%8C%E9%9D%A2) 这些昵称 和头像 如何获取&nbsp; 怎么设置

您可以参考文档中这部分内容：[设置头像和昵称](http://docs-im.easemob.com/im/android/other/easeimkit#%E8%AE%BE%E7%BD%AE%E7%94%A8%E6%88%B7%E5%A4%B4%E5%83%8F%E5%92%8C%E6%98%B5%E7%A7%B0)

**Comment by stevenwsg** [comment]
同， 这个文档看着头疼......

**Comment by jinanzhuan** [comment]
> 同， 这个文档看着头疼......

是文档结构不清晰，还是具体的功能描述不清楚？有什么建议吗？

**Comment by jinanzhuan** [comment]
官方文档板式进行了更新，请查看一下，如果有满意的地方，可以随时和我们联系，Android文档地址：http://docs-im-beta.easemob.com/document/android/quickstart.html
