### ISSUE TITLE
发现两个内存泄漏

### ISSUE THREAD

**Issue by stevenwsg** [easemob/easeui#211]
![image](https://user-images.githubusercontent.com/22788925/119661558-fe73b380-be62-11eb-8a34-28247cb38e5d.png)
这个是进入回话聊天页面发生的

![image](https://user-images.githubusercontent.com/22788925/119661559-fe73b380-be62-11eb-8ee3-8766da8ad09f.png)
这个是发语音消息 播放时遇到的

**Comment by stevenwsg** [comment]
我用的是3.8.1版本， 网易mumu模拟器


    // 环信
    implementation 'io.hyphenate:ease-im-kit:3.8.1'
    implementation 'io.hyphenate:hyphenate-chat:3.8.1'

**Comment by jinanzhuan** [comment]
> ![image](https://user-images.githubusercontent.com/22788925/119661558-fe73b380-be62-11eb-8a34-28247cb38e5d.png)
> 这个是进入回话聊天页面发生的
> 
> ![image](https://user-images.githubusercontent.com/22788925/119661559-fe73b380-be62-11eb-8ee3-8766da8ad09f.png)
> 这个是发语音消息 播放时遇到的

感谢您的反馈，我们将尽快进行修复。

**Comment by jinanzhuan** [comment]
以上两个内存泄露问题已在3.8.3版本中修复，请更新到此版本
