### ISSUE TITLE
Fragment onCreateView参数container为空，为什么不直接使用参数传递的inflater

### ISSUE THREAD

**Issue by justdoITlkq** [easemob/easeui#213]
![image](https://user-images.githubusercontent.com/21286859/120785413-affb9e80-c55f-11eb-9ef6-32d5dfcd2561.png)

**Comment by justdoITlkq** [comment]
![image](https://user-images.githubusercontent.com/21286859/120785783-0cf75480-c560-11eb-8ded-8d2cb17df5a9.png)
![image](https://user-images.githubusercontent.com/21286859/120785908-31533100-c560-11eb-82bb-7546ddb5dc93.png)

**Comment by jinanzhuan** [comment]
谢谢您的建议，后续将相应的修改为inflater.

**Comment by jinanzhuan** [comment]
已经在3.8.3版本中修改了。
