### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by stevenwsg** [easemob/easeui#214]
Couldn't find meta-data for provider with authority com.wsg.xsybbs.fileProvider

com.hyphenate.easeui.utils.EaseCompat.getUriForFile(EaseCompat.java:252)

用户反馈说是点击拍照返回时，发生了崩溃。机型是小米8。
详见：https://github.com/stevenwsg/XSYBBS/issues/7

这个是不是在3.8.2版本添加localpath修复了？

你们能不能更新一下百度地图定位的集成方式， 旧的文档现在不适合新的SDK，爆红了

**Comment by jinanzhuan** [comment]
> Couldn't find meta-data for provider with authority com.wsg.xsybbs.fileProvider
> 
> com.hyphenate.easeui.utils.EaseCompat.getUriForFile(EaseCompat.java:252)
> 
> 用户反馈说是点击拍照返回时，发生了崩溃。机型是小米8。
> 详见：[stevenwsg/XSYBBS#7](https://github.com/stevenwsg/XSYBBS/issues/7)
> 
> 这个是不是在3.8.2版本添加localpath修复了？
> 
> 你们能不能更新一下百度地图定位的集成方式， 旧的文档现在不适合新的SDK，爆红了

需要用户在AndroidManifest.xml中配置的fileProvider与EaseIMKit中一致：context.getPackageName() + ".fileProvider"

**Comment by stevenwsg** [comment]
> > Couldn't find meta-data for provider with authority com.wsg.xsybbs.fileProvider
> > com.hyphenate.easeui.utils.EaseCompat.getUriForFile(EaseCompat.java:252)
> > 用户反馈说是点击拍照返回时，发生了崩溃。机型是小米8。
> > 详见：[stevenwsg/XSYBBS#7](https://github.com/stevenwsg/XSYBBS/issues/7)
> > 这个是不是在3.8.2版本添加localpath修复了？
> > 你们能不能更新一下百度地图定位的集成方式， 旧的文档现在不适合新的SDK，爆红了
> 
> 需要用户在AndroidManifest.xml中配置的fileProvider与EaseIMKit中一致：context.getPackageName() + ".fileProvider"

能给个具体配置的文档链接嘛？我在文档上没找到这块的描述

**Comment by jinanzhuan** [comment]
> > > Couldn't find meta-data for provider with authority com.wsg.xsybbs.fileProvider
> > > com.hyphenate.easeui.utils.EaseCompat.getUriForFile(EaseCompat.java:252)
> > > 用户反馈说是点击拍照返回时，发生了崩溃。机型是小米8。
> > > 详见：[stevenwsg/XSYBBS#7](https://github.com/stevenwsg/XSYBBS/issues/7)
> > > 这个是不是在3.8.2版本添加localpath修复了？
> > > 你们能不能更新一下百度地图定位的集成方式， 旧的文档现在不适合新的SDK，爆红了
> > 
> > 
> > 需要用户在AndroidManifest.xml中配置的fileProvider与EaseIMKit中一致：context.getPackageName() + ".fileProvider"
> 
> 能给个具体配置的文档链接嘛？我在文档上没找到这块的描述

这是manifest中的provider设置：
![image](https://user-images.githubusercontent.com/19923624/125243811-28087180-e321-11eb-83e4-cb5f05f67720.png)
这是imkit中使用fileProvider:
![image](https://user-images.githubusercontent.com/19923624/125244040-6dc53a00-e321-11eb-821b-0a5981b9eaf9.png)
