### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by stevenwsg** [easemob/easeui#215]
Didn't find class "com.baidu.mapapi.SDKInitializer" on path: DexPathList[[zip file "/data/app/com.wsg.xsybbs-cV3aFZaj3ONd79ynx_aYHA==/base.apk"],nativeLibraryDirectories=[/data/app/com.wsg.xsybbs-cV3aFZaj3ONd79ynx_aYHA==/lib/arm64, /data/app/com.wsg.xsybbs-cV3aFZaj3ONd79ynx_aYHA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]

com.hyphenate.easeui.ui.EaseBaiduMapActivity.onCreate(EaseBaiduMapActivity.java:90)

我用的是3.8.1的版本。

这个是什么问题啊？一个小米8这个crash发生了五次

**Comment by stevenwsg** [comment]
是sdk里面没有集成百度定位的sdk嘛，需要我手动集成？

**Comment by jinanzhuan** [comment]
> 是sdk里面没有集成百度定位的sdk嘛，需要我手动集成？

SDK里面没有集成，如果要使用百度定位的话，需要引入相应的jar和.so文件，可以参考demo:https://github.com/easemob/chat-android 中的用法

**Comment by stevenwsg** [comment]
> > 是sdk里面没有集成百度定位的sdk嘛，需要我手动集成？
> 
> SDK里面没有集成，如果要使用百度定位的话，需要引入相应的jar和.so文件，可以参考demo:https://github.com/easemob/chat-android 中的用法

嗯嗯 好的 感谢~
