### ISSUE TITLE
发现一个内存泄漏

### ISSUE THREAD

**Issue by stevenwsg** [easemob/easeui#216]
![image](https://user-images.githubusercontent.com/22788925/121793985-1a36d200-cc37-11eb-9021-fce0162c1013.png)
这个是聊天时，发送图片成功后遇到的。
版本是3.8.1

感觉好多都是匿名类持有外部类的引用引起的

**Comment by jinanzhuan** [comment]
> ![image](https://user-images.githubusercontent.com/22788925/121793985-1a36d200-cc37-11eb-9021-fce0162c1013.png)
> 这个是聊天时，发送图片成功后遇到的。
> 版本是3.8.1
> 
> 感觉好多都是匿名类持有外部类的引用引起的

谢谢，后续我们将尽快解决类似的问题！

**Comment by jinanzhuan** [comment]
以上内存泄漏问题，已经在3.8.3版本修复，请更新一下
