### ISSUE TITLE
百度地图发送位置引起的两个内存泄露

### ISSUE THREAD

**Issue by stevenwsg** [easemob/easeui#222]
版本是3.8.3
![image](https://user-images.githubusercontent.com/22788925/126893981-1d96d576-562d-4306-8485-e74110e795b3.png)
静态内部类引起的

![image](https://user-images.githubusercontent.com/22788925/126894033-9bd04f88-7b11-4050-8e37-55445e4db045.png)

context没有及时回收

**Comment by jinanzhuan** [comment]
> 版本是3.8.3
> ![image](https://user-images.githubusercontent.com/22788925/126893981-1d96d576-562d-4306-8485-e74110e795b3.png)
> 静态内部类引起的
> 
> ![image](https://user-images.githubusercontent.com/22788925/126894033-9bd04f88-7b11-4050-8e37-55445e4db045.png)
> 
> context没有及时回收

感谢您的反馈，这个问题我们将尽快修复。

**Comment by jinanzhuan** [comment]
> 版本是3.8.3 ![image](https://user-images.githubusercontent.com/22788925/126893981-1d96d576-562d-4306-8485-e74110e795b3.png) 静态内部类引起的
> 
> ![image](https://user-images.githubusercontent.com/22788925/126894033-9bd04f88-7b11-4050-8e37-55445e4db045.png)
> 
> context没有及时回收

4.0.0版本对内存泄漏的问题进行了修复，请你试用一下这个版本及以后的版本。查看最新的版本，可以通过如下方式：https://central.sonatype.com/artifact/io.hyphenate/ease-im-kit
