### ISSUE TITLE
聊天输入布局的按钮【发送】的字体太大了，不想改成本地集成

### ISSUE THREAD

**Issue by 2993277254** [easemob/easeui#272]
你好，聊天输入按钮【发送】的字体太大了，我记成后显示不完全
我看了一下xml的布局，字体是16sp，能否提供一个方法修改字体大小，或者暴露出button这个控件

**Comment by jinanzhuan** [comment]
> 你好，聊天输入按钮【发送】的字体太大了，我记成后显示不完全 我看了一下xml的布局，字体是16sp，能否提供一个方法修改字体大小，或者暴露出button这个控件

您好，您可以通过以下方式实现修改“发送”按钮的字体等的修改：
拷贝布局文件 ease_widget_chat_primary_menu.xml 到你的应用的layout文件夹下，然后修改"btn_send"控件的字体大小即可。
