### ISSUE TITLE
android端，退群或者被踢后，sdk在群事件，直接销毁activity的问题

### ISSUE THREAD

**Issue by 2993277254** [easemob/easeui#281]
你好，android这边有个问题，
我看到聊天的类EaseChatFragment有引用EaseChatLayout,
EaseChatLayout里面监听了群组事件
  private class GroupListener extends EaseGroupListener {

        @Override
        public void onUserRemoved(String groupId, String groupName) {
            finishCurrent();
        }

        @Override
        public void onGroupDestroyed(String groupId, String groupName) {
            finishCurrent();
        }
    }

 private void finishCurrent() {
        if(getContext() instanceof Activity) {
            ((Activity) getContext()).finish();
        }
    }

里面直接销毁了activity

但是我的项目是单activity，销毁会直接干掉整个app,但是这个又无法重载，能不能提供一下自定义的方法

**Comment by jinanzhuan** [comment]
> 你好，android这边有个问题， 我看到聊天的类EaseChatFragment有引用EaseChatLayout, EaseChatLayout里面监听了群组事件 private class GroupListener extends EaseGroupListener {
> 
> ```
>     @Override
>     public void onUserRemoved(String groupId, String groupName) {
>         finishCurrent();
>     }
> 
>     @Override
>     public void onGroupDestroyed(String groupId, String groupName) {
>         finishCurrent();
>     }
> }
> ```
> 
> private void finishCurrent() { if(getContext() instanceof Activity) { ((Activity) getContext()).finish(); } }
> 
> 里面直接销毁了activity
> 
> 但是我的项目是单activity，销毁会直接干掉整个app,但是这个又无法重载，能不能提供一下自定义的方法

感谢您的反馈，我们将尽快处理这个问题，预计会将销毁Activity的逻辑放到EaseChatFragment中，并且将这个方法public。

**Comment by jinanzhuan** [comment]
您好，关于销毁Activity，导致您项目被杀掉的问题，我们已经在 4.0.2 版本中，在EaseChatFragment中暴露了 public 的方法 onChatFinish ，它的默认实现为销毁当前的acitivty，您可以通过复写这个方法，修改对应的逻辑。
另，4.0.2 远程库地址为：implementation 'io.hyphenate:ease-im-kit:4.0.2'。
最后感谢您对uikit这个产品的使用和关注，如果您在使用过程中遇到不合理或者使用不方便的地方，请您通过issue及时反馈给我们。
