### ISSUE TITLE
开启混淆打包  R8编译异常

### ISSUE THREAD

**Issue by Lucklyheart** [easemob/easeui#290]
![image](https://github.com/easemob/easeui/assets/33649270/d80e9ba6-7a8e-41b8-ad84-9c8509a43d0d)
请问有遇到这种情况嘛？

**Comment by Lucklyheart** [comment]
![image](https://github.com/easemob/easeui/assets/33649270/0fd3593d-99ed-4e2b-8ce7-244b3afbacce)
集成了sdk和ui库

**Comment by jinanzhuan** [comment]
> ![image](https://user-images.githubusercontent.com/33649270/240185489-d80e9ba6-7a8e-41b8-ad84-9c8509a43d0d.png) 请问有遇到这种情况嘛？

看着是因为你开启混淆后找不到对应的类了，参考你使用的三方库：https://github.com/daimajia/AnimationEasingFunctions 中提到的混淆规则
