### ISSUE TITLE
EaseChatRow代码有个bug

### ISSUE THREAD

**Issue by LiuYimin** [easemob/easeui#292]
protected void setAvatarAndNick() {
        if (isSender()) {
            //只要不是常规布局形式，就展示昵称
            if(EaseChatItemStyleHelper.getInstance().getStyle().getItemShowType() != EaseChatMessageListLayout.ShowType.NORMAL.ordinal()) {
                if (message.getChatType() == EMMessage.ChatType.GroupChat){
                    EaseUserUtils.setUserAvatar(context, message.conversationId(), message.getFrom(), userAvatarView);
                    EaseUserUtils.setUserNick(message.conversationId(),message.getFrom(),usernickView);
                }else {
                    EaseUserUtils.setUserNick(message.getFrom(), usernickView);
                    EaseUserUtils.setUserAvatar(context, message.getFrom(), userAvatarView);
                }
            }
        } else {
            if (message.getChatType() == EMMessage.ChatType.GroupChat){
                EaseUserUtils.setUserNick(message.conversationId(),message.getFrom(), usernickView);
                EaseUserUtils.setUserAvatar(context, message.conversationId(), message.getFrom(), userAvatarView);
            }else {
                EaseUserUtils.setUserNick(message.getFrom(), usernickView);
                EaseUserUtils.setUserAvatar(context, message.getFrom(), userAvatarView);
            }
        }
    }
388行
这个bug导致在消息列表中,自己发的消息,头像始终是默认头像.这点也体现在 完整版的demo中,希望能更新修复.

**Comment by jinanzhuan** [comment]
感谢您的反馈，这个问题将在4.0.3版本中修复。

**Comment by jinanzhuan** [comment]
> protected void setAvatarAndNick() { if (isSender()) { //只要不是常规布局形式，就展示昵称 if(EaseChatItemStyleHelper.getInstance().getStyle().getItemShowType() != EaseChatMessageListLayout.ShowType.NORMAL.ordinal()) { if (message.getChatType() == EMMessage.ChatType.GroupChat){ EaseUserUtils.setUserAvatar(context, message.conversationId(), message.getFrom(), userAvatarView); EaseUserUtils.setUserNick(message.conversationId(),message.getFrom(),usernickView); }else { EaseUserUtils.setUserNick(message.getFrom(), usernickView); EaseUserUtils.setUserAvatar(context, message.getFrom(), userAvatarView); } } } else { if (message.getChatType() == EMMessage.ChatType.GroupChat){ EaseUserUtils.setUserNick(message.conversationId(),message.getFrom(), usernickView); EaseUserUtils.setUserAvatar(context, message.conversationId(), message.getFrom(), userAvatarView); }else { EaseUserUtils.setUserNick(message.getFrom(), usernickView); EaseUserUtils.setUserAvatar(context, message.getFrom(), userAvatarView); } } } 388行 这个bug导致在消息列表中,自己发的消息,头像始终是默认头像.这点也体现在 完整版的demo中,希望能更新修复.

您反馈的问题，已在uikit 4.0.3版本中修复，远程仓库 mavenCentral，远程依赖：implementation 'io.hyphenate:ease-im-kit:4.0.3'。再次对您的支持表示感谢！
