### ISSUE TITLE
主分支缺少文件

### ISSUE THREAD

**Issue by tianshaokai** [easemob/easeui#63]
import com.easemob.util.EMLog;

import com.easemob.chat.EMChatManager;
import com.easemob.chat.EMChatRoom;
import com.easemob.chat.EMConversation;
import com.easemob.chat.EMConversation.EMConversationType;
import com.easemob.chat.EMGroup;
import com.easemob.chat.EMGroupManager;
import com.easemob.chat.EMMessage;
import com.easemob.chat.EMMessage.Direct;

我下载的主分支代码少这几个类啊

**Comment by francisCN** [comment]
主分支是2.x的,最新版分支为easeui-release_3.1.2

**Comment by greatflag** [comment]
都没有EMLog

**Comment by tianshaokai** [comment]
@greatflag  那缺少了那个文件，去哪找呢

**Comment by greatflag** [comment]
@tianshaokai 官网下载最新版的SDK，里面包含的demo直接导入studio就能运行。
