### ISSUE TITLE
缺少jar包

### ISSUE THREAD

**Issue by jiangmeng1** [easemob/easeui#69]
com.easemob.redpacketsdk.RedPacket，提示这个类没有。很多类找不到。redparketlibrary这个库不存在。

**Comment by githubzhaoliang** [comment]
redpacketsdk 在demo中，你easeui和demo一起在用吗？

**Comment by jiangmeng1** [comment]
谢谢。我想先看看这个demo。不用的话，有些东西也是可以借鉴的。
