### ISSUE TITLE
缺少java文件

### ISSUE THREAD

**Issue by Seasonxx** [easemob/easeui#89]
EaseEmojiconScrollTabBar这个文件中使用了DensityUtil，但是在easeui中并没有这文件，希望核实后提交一下

**Comment by zhanw** [comment]
EaseUI依赖环信sdk，DensityUtil类在sdk里

**Comment by Seasonxx** [comment]
@zhanw 
现在代码里的是这样引入的：import com.easemob.util.DensityUtil，所以报错；
把这行代码删除后重新引入变成这样：import com.hyphenate.util.DensityUtil，就不报错了。
如果可以的话还希望你们能改一下，还是有些小误导呢(^-^)
